### ISSUE TITLE
Scalable Infrastructure Maps

### ISSUE THREAD

**Issue by sorantis** [elastic/infrastructure#17]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)
Today the waffle map does not scale to large environments with 10,000 - 100,000 nodes, which leads to several issues with user experience:
- Details (name, metric) disappear at small sizes
- Hard to see any information for large deployments
- Hard to navigate the map

**User stories**
As a DevOps engineer I want to be able to easily navigate my infrastructure inventory irrespective of its size so that I could
- better customize my views
- switch between micro and macro perspectives
- access details of any resource in my inventory
- spot any "hot" resources and quickly zoom into that part of my inventory

**List known (technical) restrictions and requirements**
has to be able to scale large physical and virtual infrastructures. 

Product Brief: https://github.com/elastic/observability-dev/issues/898

**Comment by smith** [comment]
Not prioritizing this at this time.
