### ISSUE TITLE
Multiple Severity Levels in Threshold Alerts

### ISSUE THREAD

**Issue by sorantis** [elastic/infrastructure#19]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)
Today our threshold alerts support only one default severity level. We've been getting consistent feedback from customers asking to introduce multiple severity levels, e.g. `warning`, `critical`. The Kibana alerting team has been working on some design mockups for multi-level notifications, which can be found [here](https://github.com/elastic/dev/issues/1422).
Also, different companies have different policies on severity levels, and these levels can differ in name or amount (see my comment [here](https://github.com/elastic/dev/issues/1422#issuecomment-636915238)). 
The Kibana alerting team will be working on implementation of this, we will need to incorporate multiple severity levels in our alerts. Note, this can (and probably will) be applicable to other observability types.

**User stories**
As a DevOps engineer I want to be able to set multiple threshold values based on severity levels, so that I could channel notifications based on the severity levels.

**Comment by katrin-freihofner** [comment]
@sorantis, this is a feature that is going to be provided by the Kibana alerting team. 
I'm not sure what exactly you expect us to do. Also, I think this should be an Kibana/Observability wide initiative.

**Comment by sorantis** [comment]
I think the Kibana alerting team will provide this functionality at the framework level. We'll need to expose it in the alert fly-out and make severity levels work with multiple conditions.

**Comment by tbragin** [comment]
@katrin-freihofner makes a good point about exposing alert severity levels consistently across observability alerts.

@cyrille-leclerc @mukeshelastic would you agree this concept applies equally well to APM, Uptime, and Logs alerts?

@sorantis @mukeshelastic do we have an indication yet of when Kibana will support alert severity levels?

**Comment by cyrille-leclerc** [comment]
Thanks for the research @sorantis .

Here are few observations
* **Yes, the concept of severity applies to all domains of Observability (APM, RUM, Synthetics, logs and metrics)**
* Having multiple thresholds per alert assigning different severities is great (les duplication of alerts + better UI) and is common in our industry.
* I see connection between alert severity and
   * logs: log severity messages
   * observability events: alerts can be seen as events that report problems. The severity of Observability Events can include the "INFO" level in addition to all the levels used for alerts (e.g. "WARN", "ERROR" and CRITICAL")
* The OpenTelemetry logs specification has done an interesting inventory of various Observability messages structures (syslog, windows event log...) including the severity qualifiers: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/logs/data-model.md#appendix-a-example-mappings

Here are some severity levels that I would like to evaluate

* `error`: the "basic" level that reports that something goes wrong (e.g. some customers are facing errors )
* `warning`: the level that reports that things are not very good but not yet an error (e.g. degraded response time)
* `fatal` (aka `critical`): the very serious problem, a service is completely KO, all customers are facing errors (e.g. the service crashed or always returns an error)
* `info`: maybe not relevant for alerts but relevant for notification messages
