### ISSUE TITLE
Custom links in Metrics UI

### ISSUE THREAD

**Issue by sorantis** [elastic/infrastructure#22]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)
Multiple users have expressed the need to add custom links to resources on inventory, specifically attaching a dashboard, or adding a reference to another page. We already provide custom links in APM, Security apps, but there's no such capability in Metrics UI.

**User stories**
As an admin, I want to be able to link to other sources from Metrics UI, so that i didn't have to manually keep an inventory of related URLs that could help me with my troubleshooting workflows.

**Comment by sorantis** [comment]
Related issue: https://github.com/elastic/kibana/issues/21884

**Comment by katrin-freihofner** [comment]
This could be part of the node details enhancement. The context menu is maybe going to be replaced by a flyout.

Do we have any data on the usage of this feature in APM?
