### ISSUE TITLE
Save Map View in Infrastructure

### ISSUE THREAD

**Issue by icefish-creativ** [elastic/infrastructure#3]
many thanks that now custom fields at "Group by" available , i think it were nice that build a Map View with Custom fields and save them . so i have multiple "source"

cheers 

Tim

**Comment by makwarth** [comment]
Hi @icefish-creativ. To clarify, you would like the ability to have multiple custom fields in the dropdown? For your use case, should these custom fields be stored in localstorage or as part of the "Source" configuration?

**Comment by icefish-creativ** [comment]
Hi @makwarth ,

as part of the "source" , if I'm being right there is only one "source" possible , that can only be renamed. more then one "source" were great.At the moment you can only get a maximum of 2 customs fields ,up to 5 were great too.

**Comment by makwarth** [comment]
Got it, thanks!

**Comment by icefish-creativ** [comment]
thank you for the great tool

**Comment by jasonrhodes** [comment]
@elastic/infra-logs-ui is this the same as "source switching" mentioned here: elastic/kibana#20662

**Comment by jasonrhodes** [comment]
If we're keeping this we should move it to the kibana repo.

**Comment by weltenwort** [comment]
> is this the same as "source switching" mentioned here

If I understand this enhancement request correctly, this is about persisting a "group by" setting. Right now it's only persisted in the URL.

It would be possible to add configuration for the default filter, metric and group by values along with the source. In this case the source switching UI would become more valuable to switch between presets.

Alternatively the source could have a list of preset values to choose from when viewing the source. In this case the source *has* a set of preset configuration as opposed to *being* a preset configuration.
