### ISSUE TITLE
Azure Account for Christine Komander

### ISSUE THREAD

**Issue by ChristineKomander** [elastic/infrastructure#4]
Hi there, 
could somebody please help me with providing an Elastic Azure Account in order to prepare a joint Webinar with Microsoft, for which I need to setup a demo environment using VMs, AKS, Event Hubs and some more services available in the portal ?
Have started with my private account but ran out of resources for that. 
Thanks,
Christine

**Comment by drewr** [comment]
I've moved this to the correct repo.
