### ISSUE TITLE
Improve browsing metrics UX

### ISSUE THREAD

**Issue by hbharding** [elastic/infrastructure#8]
Related: https://github.com/elastic/kibana/issues/40120

## Summary of the problem

![image](https://user-images.githubusercontent.com/847805/70829020-9ccca000-1dba-11ea-9f75-c5a2e5c59a85.png)

When using Metrics Explorer or the Inventory view, there are so many metrics to choose from that it can be difficult to make a decision. The UI only presents a few in a small dropdown menu that is ordered alphabetically (hello, looking at you `agent.*`).  It is also difficult to know which metrics will yield interesting results because many of the metrics return nothing. 

## Ideal solution

Some initial ideas. In addition to what's already covered in https://github.com/elastic/kibana/issues/40120, It would be nice if:
- you could see all available modules in a single view. This may help users know where to start their search from (Kubernetes, Apache, AWS, etc.)
- see a list of recently used or related metrics so that the user doesn't haven't to retype the entire metric namespaces.
- the UI somehow removes / disables metrics for which there is no data
- the UI can generate a quick preview of for the metric's data. This could help users feel confident when they are deciding to add a metric. Lens does a good job with this.

## known (technical) restrictions and requirements
Not sure / need to check.

**Comment by sorantis** [comment]
Just noticed that the Aggregations dropdown uses a similar approach for categorizing different agg types.  <img width="1272" alt="Screen Shot 2020-03-10 at 19 22 52" src="https://user-images.githubusercontent.com/1685068/76346072-b8393f80-6304-11ea-9dd0-f2589629e73f.png">

**Comment by tbragin** [comment]
@katrin-freihofner I noticed this ticket closed. Do we have a resolution?

**Comment by katrin-freihofner** [comment]
@tbragin I mixed things up. I'm going to reopen it.

**Comment by sorantis** [comment]
Bumping this up, since with the new indexing strategy it should be simpler to only show the fields form enabled integrations.

**Comment by smith** [comment]
Not prioritizing this at this time.
